
package org.targetas.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TargetaServiceImplService", targetNamespace = "http://service.targetas.org/", wsdlLocation = "http://localhost:8085/TargetasOnline/TargetaService?wsdl")
public class TargetaServiceImplService
    extends Service
{

    private final static URL TARGETASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TARGETASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TARGETASERVICEIMPLSERVICE_QNAME = new QName("http://service.targetas.org/", "TargetaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/TargetasOnline/TargetaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARGETASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TARGETASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TargetaServiceImplService() {
        super(__getWsdlLocation(), TARGETASERVICEIMPLSERVICE_QNAME);
    }

    public TargetaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARGETASERVICEIMPLSERVICE_QNAME, features);
    }

    public TargetaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TARGETASERVICEIMPLSERVICE_QNAME);
    }

    public TargetaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARGETASERVICEIMPLSERVICE_QNAME, features);
    }

    public TargetaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TargetaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TargetaService
     */
    @WebEndpoint(name = "TargetaServiceImplPort")
    public TargetaService getTargetaServiceImplPort() {
        return super.getPort(new QName("http://service.targetas.org/", "TargetaServiceImplPort"), TargetaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TargetaService
     */
    @WebEndpoint(name = "TargetaServiceImplPort")
    public TargetaService getTargetaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.targetas.org/", "TargetaServiceImplPort"), TargetaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARGETASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TARGETASERVICEIMPLSERVICE_EXCEPTION;
        }
        return TARGETASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
